version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "17:00"
    timezone: Europe/Warsaw
  open-pull-requests-limit: 99
  target-branch: dev
  reviewers:
  - TheChilliPL
  assignees:
  - TheChilliPL
